### ISSUE TITLE
Host directory permission denied

### ISSUE THREAD

**Issue by farhanrahman** [RafalWilinski/elastic-beanstalk-terraform-setup#1]
Hi,

I have been trying to get it running with an elastic search cluster but the host volume cannot be accessed from the docker container. I have edited the dockerrun.aws.json file to add the new volume which looks something like this:
```    "Volumes": [
    {
        "HostDirectory": "esdata",
        "ContainerDirectory": "/var/esdata"
    },
    {
        "HostDirectory": "log",
        "ContainerDirectory": "/var/log"
    }]
```

Still I get permission denied exception. Any idea what could be wrong here?

**Comment by RafalWilinski** [comment]
Yep, I think I've faced similar issue when trying to run with custom volumes. Can you post exception that you're getting? Is it purely IAM related or is it connected with Docker/Beanstalk layer?

**Comment by farhanrahman** [comment]
Hi. Thanks for the quick reply. I managed to fix the problems. The problem wasn't actually in the host directory. I was mapping a non-existent container directory into the host volume. I expected elasticsearch to create those directories actually but unfortunately it didn't. Here is a Dockerrun.aws.template.json file (the template because the <*> gets replaced with actual values)
```
{
    "AWSEBDockerrunVersion": "1",
    "Image": {
        "Name": "<AWS_ACCOUNT_ID>.dkr.ecr.<REGION>.amazonaws.com/<NAME>:<TAG>",
        "Update": "true"
    },
    "Ports": [
    {
        "ContainerPort": "80"
    },
    {
        "ContainerPort": "9200"
    },
    {
        "ContainerPort": "9300"
    }],
    "Volumes": [
    {
        "HostDirectory": "/var/app/esdata",
        "ContainerDirectory": "/usr/share/elasticsearch/data" // <--was "/var/esdata"
    },
    {
        "HostDirectory": "/var/app/log",
        "ContainerDirectory": "/usr/share/elasticsearch/logs" //<--was "/var/log/"
    }]
}
```

Thank you for this repository. It helped me massively. Both terraform and elastic beanstalk documentation isn't really extensive enough to cover a simple bringup.

**Comment by farhanrahman** [comment]
Just fixed the problem now so i'll close the issue.

**Comment by RafalWilinski** [comment]
Glad to see that you've fixed your issue, thanks for explaining!
