### ISSUE TITLE
Unable to launch application as the source bundle does not contain either a file named application.jar or a Procfile.

### ISSUE THREAD

**Issue by just4give** [RafalWilinski/elastic-beanstalk-terraform-setup#2]
Hi there,
I tried to follow your instructions and created a zip file containing only Dockerrun.aws.json and deployed the zip file. But I am receiving below error. Do you have any clue? Definitely I am not packaging the jar file as I am expecting that to be pulled from ECR as described in Dockerrun.aws.json
```
Unable to launch application as the source bundle does not contain either a file named application.jar or a Procfile.
```

**Comment by just4give** [comment]
Never mind... I figured it out.

**Comment by shaun-wild** [comment]
You gonna offer any insight for other people with the same issue?

**Comment by just4give** [comment]
I wish I wrote how I solved that. Are you having the same problem? Unfortunately I forgot what was the resolution.. will try to recall .... most probably I had to add expose port 5000 in the Dockerfile

**Comment by shaun-wild** [comment]
I also figured it out! thank god.

My source bundle was simply incorrect. I was exporting a zip file as an artifact from my CodePipeline instead of a list of the files to put in the source bundle.
